### ISSUE TITLE
branch support

### ISSUE THREAD

**Issue by azachar** [blakawk/gitlab-integration#20]
Hello, I would like to see the latest pipeline that belongs to that branch.

Do you plan to support it?

Showing only the one pipeline from the top of all pipelines I found a bit useless. 

What makes sense is to see directly what is wrong with jobs in the pipeline of the current. For example, if a branch pipeline's job fails, open the log file within Atom. But I guess this is another issue :).

Anyway, thank you in advance for considering. 

Cheers,
Andrej

**Comment by blakawk** [comment]
@azachar I took your request into account regarding branches, it was indeed a good proposition.

Regarding the opening of the failed logs, it is also interesting, but need more time to be implemented. Issue #22 has been opened to track this.

**Comment by azachar** [comment]
Fantastic, what a great job!

**Comment by azachar** [comment]
I just check the implementation and I wonder how the event "change branch" is caught and propagated.  Does Atom handle this somehow? It seems to me that always I need to reload the whole atom, to pick up the changed branch.

**Comment by blakawk** [comment]
The change branch event is not caught or propagated by atom, and I do not
seem to find any way to subscribe to such event in Atom API.

However, the pipelines are retrieved only every 4 seconds (depending on the
package settings), and as such, the new pipeline statuses according to the
project's current branch will be displayed. You only just need to wait some
time in order to have the changed branch picked up. Keep me in touch.

Le mar. 12 déc. 2017 à 13:26, Andrej Zachar <notifications@github.com> a
écrit :
