### ISSUE TITLE
[Request] Wiki user instructions

### ISSUE THREAD

**Issue by ghost** [blakawk/gitlab-integration#40]
I've created a Gitlab account and added the key to the plugin. I can not see how to check in my code, or how to choose the new/empty project I have created on Gitlab. 

Any help appreciated. This would make good wiki information.

**Comment by blakawk** [comment]
@tenleftfingers indeed it would be good to put that in the README, i'll try to do so. In the mean time, you can follow https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html#clone-a-repository in order to clone your new repository and then https://flight-manual.atom.io/getting-started/sections/atom-basics/#opening-directories in order to open your repository.

If you follow theses steps and start using gitlab CI (https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html), the plugin will show your pipelines statuses in Atom status bar.

**Comment by ghost** [comment]
Thanks blakawk.
